# fly.toml app configuration file generated for mapclientes-backend on 2025-07-16T14:34:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mapclientes-backend'
primary_region = 'eze'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '60s'
    timeout = '30s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/ping'
    protocol = 'http'
    tls_skip_verify = false
    
    # Configuración adicional para evitar suspensión
    [http_service.checks.headers]
      "User-Agent" = "Fly Health Check"

[[vm]]
  size = 'shared-cpu-1x'
  processes = ['app']

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/static/'
